/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthTransactionsRouteImport } from './routes/_auth.transactions'
import { Route as AuthPortfolioRouteImport } from './routes/_auth.portfolio'
import { Route as AuthComponentTestingRouteImport } from './routes/_auth.component-testing'
import { Route as AuthTransactionsIndividualRouteImport } from './routes/_auth.transactions.individual'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTransactionsRoute = AuthTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPortfolioRoute = AuthPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthRoute,
} as any)
const AuthComponentTestingRoute = AuthComponentTestingRouteImport.update({
  id: '/component-testing',
  path: '/component-testing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTransactionsIndividualRoute =
  AuthTransactionsIndividualRouteImport.update({
    id: '/individual',
    path: '/individual',
    getParentRoute: () => AuthTransactionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/component-testing': typeof AuthComponentTestingRoute
  '/portfolio': typeof AuthPortfolioRoute
  '/transactions': typeof AuthTransactionsRouteWithChildren
  '/': typeof AuthIndexRoute
  '/transactions/individual': typeof AuthTransactionsIndividualRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/component-testing': typeof AuthComponentTestingRoute
  '/portfolio': typeof AuthPortfolioRoute
  '/transactions': typeof AuthTransactionsRouteWithChildren
  '/': typeof AuthIndexRoute
  '/transactions/individual': typeof AuthTransactionsIndividualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_auth/component-testing': typeof AuthComponentTestingRoute
  '/_auth/portfolio': typeof AuthPortfolioRoute
  '/_auth/transactions': typeof AuthTransactionsRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/transactions/individual': typeof AuthTransactionsIndividualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/login'
    | '/component-testing'
    | '/portfolio'
    | '/transactions'
    | '/'
    | '/transactions/individual'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/component-testing'
    | '/portfolio'
    | '/transactions'
    | '/'
    | '/transactions/individual'
  id:
    | '__root__'
    | '/_auth'
    | '/about'
    | '/login'
    | '/_auth/component-testing'
    | '/_auth/portfolio'
    | '/_auth/transactions'
    | '/_auth/'
    | '/_auth/transactions/individual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/transactions': {
      id: '/_auth/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthTransactionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/portfolio': {
      id: '/_auth/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthPortfolioRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/component-testing': {
      id: '/_auth/component-testing'
      path: '/component-testing'
      fullPath: '/component-testing'
      preLoaderRoute: typeof AuthComponentTestingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/transactions/individual': {
      id: '/_auth/transactions/individual'
      path: '/individual'
      fullPath: '/transactions/individual'
      preLoaderRoute: typeof AuthTransactionsIndividualRouteImport
      parentRoute: typeof AuthTransactionsRoute
    }
  }
}

interface AuthTransactionsRouteChildren {
  AuthTransactionsIndividualRoute: typeof AuthTransactionsIndividualRoute
}

const AuthTransactionsRouteChildren: AuthTransactionsRouteChildren = {
  AuthTransactionsIndividualRoute: AuthTransactionsIndividualRoute,
}

const AuthTransactionsRouteWithChildren =
  AuthTransactionsRoute._addFileChildren(AuthTransactionsRouteChildren)

interface AuthRouteChildren {
  AuthComponentTestingRoute: typeof AuthComponentTestingRoute
  AuthPortfolioRoute: typeof AuthPortfolioRoute
  AuthTransactionsRoute: typeof AuthTransactionsRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthComponentTestingRoute: AuthComponentTestingRoute,
  AuthPortfolioRoute: AuthPortfolioRoute,
  AuthTransactionsRoute: AuthTransactionsRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
