/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthUserAssetsRouteImport } from './routes/_auth.user-assets'
import { Route as AuthTransactionsRouteImport } from './routes/_auth.transactions'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthPortfolioOverviewRouteImport } from './routes/_auth.portfolio-overview'
import { Route as AuthPortfolioRouteImport } from './routes/_auth.portfolio'
import { Route as AuthComponentTestingRouteImport } from './routes/_auth.component-testing'
import { Route as AuthUserAssetsIndexRouteImport } from './routes/_auth.user-assets.index'
import { Route as AuthTransactionsIndexRouteImport } from './routes/_auth.transactions.index'
import { Route as AuthUserAssetsAssetIdRouteImport } from './routes/_auth.user-assets.$assetId'
import { Route as AuthTransactionsIndividualRouteImport } from './routes/_auth.transactions.individual'
import { Route as AuthSettingsCategoriesRouteImport } from './routes/_auth.settings.categories'
import { Route as AuthSettingsAccountsRouteImport } from './routes/_auth.settings.accounts'
import { Route as AuthAccountsAccountIdRouteImport } from './routes/_auth.accounts.$accountId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUserAssetsRoute = AuthUserAssetsRouteImport.update({
  id: '/user-assets',
  path: '/user-assets',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTransactionsRoute = AuthTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPortfolioOverviewRoute = AuthPortfolioOverviewRouteImport.update({
  id: '/portfolio-overview',
  path: '/portfolio-overview',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPortfolioRoute = AuthPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthRoute,
} as any)
const AuthComponentTestingRoute = AuthComponentTestingRouteImport.update({
  id: '/component-testing',
  path: '/component-testing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUserAssetsIndexRoute = AuthUserAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthUserAssetsRoute,
} as any)
const AuthTransactionsIndexRoute = AuthTransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthTransactionsRoute,
} as any)
const AuthUserAssetsAssetIdRoute = AuthUserAssetsAssetIdRouteImport.update({
  id: '/$assetId',
  path: '/$assetId',
  getParentRoute: () => AuthUserAssetsRoute,
} as any)
const AuthTransactionsIndividualRoute =
  AuthTransactionsIndividualRouteImport.update({
    id: '/individual',
    path: '/individual',
    getParentRoute: () => AuthTransactionsRoute,
  } as any)
const AuthSettingsCategoriesRoute = AuthSettingsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsAccountsRoute = AuthSettingsAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthAccountsAccountIdRoute = AuthAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/component-testing': typeof AuthComponentTestingRoute
  '/portfolio': typeof AuthPortfolioRoute
  '/portfolio-overview': typeof AuthPortfolioOverviewRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/transactions': typeof AuthTransactionsRouteWithChildren
  '/user-assets': typeof AuthUserAssetsRouteWithChildren
  '/accounts/$accountId': typeof AuthAccountsAccountIdRoute
  '/settings/accounts': typeof AuthSettingsAccountsRoute
  '/settings/categories': typeof AuthSettingsCategoriesRoute
  '/transactions/individual': typeof AuthTransactionsIndividualRoute
  '/user-assets/$assetId': typeof AuthUserAssetsAssetIdRoute
  '/transactions/': typeof AuthTransactionsIndexRoute
  '/user-assets/': typeof AuthUserAssetsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/component-testing': typeof AuthComponentTestingRoute
  '/portfolio': typeof AuthPortfolioRoute
  '/portfolio-overview': typeof AuthPortfolioOverviewRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/': typeof AuthIndexRoute
  '/accounts/$accountId': typeof AuthAccountsAccountIdRoute
  '/settings/accounts': typeof AuthSettingsAccountsRoute
  '/settings/categories': typeof AuthSettingsCategoriesRoute
  '/transactions/individual': typeof AuthTransactionsIndividualRoute
  '/user-assets/$assetId': typeof AuthUserAssetsAssetIdRoute
  '/transactions': typeof AuthTransactionsIndexRoute
  '/user-assets': typeof AuthUserAssetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_auth/component-testing': typeof AuthComponentTestingRoute
  '/_auth/portfolio': typeof AuthPortfolioRoute
  '/_auth/portfolio-overview': typeof AuthPortfolioOverviewRoute
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/transactions': typeof AuthTransactionsRouteWithChildren
  '/_auth/user-assets': typeof AuthUserAssetsRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/accounts/$accountId': typeof AuthAccountsAccountIdRoute
  '/_auth/settings/accounts': typeof AuthSettingsAccountsRoute
  '/_auth/settings/categories': typeof AuthSettingsCategoriesRoute
  '/_auth/transactions/individual': typeof AuthTransactionsIndividualRoute
  '/_auth/user-assets/$assetId': typeof AuthUserAssetsAssetIdRoute
  '/_auth/transactions/': typeof AuthTransactionsIndexRoute
  '/_auth/user-assets/': typeof AuthUserAssetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/component-testing'
    | '/portfolio'
    | '/portfolio-overview'
    | '/settings'
    | '/transactions'
    | '/user-assets'
    | '/accounts/$accountId'
    | '/settings/accounts'
    | '/settings/categories'
    | '/transactions/individual'
    | '/user-assets/$assetId'
    | '/transactions/'
    | '/user-assets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/component-testing'
    | '/portfolio'
    | '/portfolio-overview'
    | '/settings'
    | '/'
    | '/accounts/$accountId'
    | '/settings/accounts'
    | '/settings/categories'
    | '/transactions/individual'
    | '/user-assets/$assetId'
    | '/transactions'
    | '/user-assets'
  id:
    | '__root__'
    | '/_auth'
    | '/about'
    | '/login'
    | '/_auth/component-testing'
    | '/_auth/portfolio'
    | '/_auth/portfolio-overview'
    | '/_auth/settings'
    | '/_auth/transactions'
    | '/_auth/user-assets'
    | '/_auth/'
    | '/_auth/accounts/$accountId'
    | '/_auth/settings/accounts'
    | '/_auth/settings/categories'
    | '/_auth/transactions/individual'
    | '/_auth/user-assets/$assetId'
    | '/_auth/transactions/'
    | '/_auth/user-assets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/user-assets': {
      id: '/_auth/user-assets'
      path: '/user-assets'
      fullPath: '/user-assets'
      preLoaderRoute: typeof AuthUserAssetsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/transactions': {
      id: '/_auth/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthTransactionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/portfolio-overview': {
      id: '/_auth/portfolio-overview'
      path: '/portfolio-overview'
      fullPath: '/portfolio-overview'
      preLoaderRoute: typeof AuthPortfolioOverviewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/portfolio': {
      id: '/_auth/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthPortfolioRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/component-testing': {
      id: '/_auth/component-testing'
      path: '/component-testing'
      fullPath: '/component-testing'
      preLoaderRoute: typeof AuthComponentTestingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/user-assets/': {
      id: '/_auth/user-assets/'
      path: '/'
      fullPath: '/user-assets/'
      preLoaderRoute: typeof AuthUserAssetsIndexRouteImport
      parentRoute: typeof AuthUserAssetsRoute
    }
    '/_auth/transactions/': {
      id: '/_auth/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthTransactionsIndexRouteImport
      parentRoute: typeof AuthTransactionsRoute
    }
    '/_auth/user-assets/$assetId': {
      id: '/_auth/user-assets/$assetId'
      path: '/$assetId'
      fullPath: '/user-assets/$assetId'
      preLoaderRoute: typeof AuthUserAssetsAssetIdRouteImport
      parentRoute: typeof AuthUserAssetsRoute
    }
    '/_auth/transactions/individual': {
      id: '/_auth/transactions/individual'
      path: '/individual'
      fullPath: '/transactions/individual'
      preLoaderRoute: typeof AuthTransactionsIndividualRouteImport
      parentRoute: typeof AuthTransactionsRoute
    }
    '/_auth/settings/categories': {
      id: '/_auth/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof AuthSettingsCategoriesRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/accounts': {
      id: '/_auth/settings/accounts'
      path: '/accounts'
      fullPath: '/settings/accounts'
      preLoaderRoute: typeof AuthSettingsAccountsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/accounts/$accountId': {
      id: '/_auth/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AuthAccountsAccountIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthSettingsRouteChildren {
  AuthSettingsAccountsRoute: typeof AuthSettingsAccountsRoute
  AuthSettingsCategoriesRoute: typeof AuthSettingsCategoriesRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsAccountsRoute: AuthSettingsAccountsRoute,
  AuthSettingsCategoriesRoute: AuthSettingsCategoriesRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthTransactionsRouteChildren {
  AuthTransactionsIndividualRoute: typeof AuthTransactionsIndividualRoute
  AuthTransactionsIndexRoute: typeof AuthTransactionsIndexRoute
}

const AuthTransactionsRouteChildren: AuthTransactionsRouteChildren = {
  AuthTransactionsIndividualRoute: AuthTransactionsIndividualRoute,
  AuthTransactionsIndexRoute: AuthTransactionsIndexRoute,
}

const AuthTransactionsRouteWithChildren =
  AuthTransactionsRoute._addFileChildren(AuthTransactionsRouteChildren)

interface AuthUserAssetsRouteChildren {
  AuthUserAssetsAssetIdRoute: typeof AuthUserAssetsAssetIdRoute
  AuthUserAssetsIndexRoute: typeof AuthUserAssetsIndexRoute
}

const AuthUserAssetsRouteChildren: AuthUserAssetsRouteChildren = {
  AuthUserAssetsAssetIdRoute: AuthUserAssetsAssetIdRoute,
  AuthUserAssetsIndexRoute: AuthUserAssetsIndexRoute,
}

const AuthUserAssetsRouteWithChildren = AuthUserAssetsRoute._addFileChildren(
  AuthUserAssetsRouteChildren,
)

interface AuthRouteChildren {
  AuthComponentTestingRoute: typeof AuthComponentTestingRoute
  AuthPortfolioRoute: typeof AuthPortfolioRoute
  AuthPortfolioOverviewRoute: typeof AuthPortfolioOverviewRoute
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthTransactionsRoute: typeof AuthTransactionsRouteWithChildren
  AuthUserAssetsRoute: typeof AuthUserAssetsRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAccountsAccountIdRoute: typeof AuthAccountsAccountIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthComponentTestingRoute: AuthComponentTestingRoute,
  AuthPortfolioRoute: AuthPortfolioRoute,
  AuthPortfolioOverviewRoute: AuthPortfolioOverviewRoute,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthTransactionsRoute: AuthTransactionsRouteWithChildren,
  AuthUserAssetsRoute: AuthUserAssetsRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  AuthAccountsAccountIdRoute: AuthAccountsAccountIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
