export const QueryKeys = {
  AUTH_ME: "auth-me",
  PORTFOLIO_HISTORY: "portfolio",
  PORTFOLIO_HOLDINGS: "holdings",
  ASSETS: "assets",
  USER_CATEGORIES: "user-categories",
  USER_CATEGORY_TYPES: "user-category-types",
  GLOBAL_CATEGORIES: "global-categories",
  INDIVIDUAL_TRANSACTIONS: "individual-transactions",
  ACCOUNTS: "accounts",
  USER_ACCOUNTS: "user-accounts",
  ACCOUNT_TYPES: "account-types",
  ACCOUNT_LIQUIDITY_TYPES: "account-liquidity-types",
  PORTFOLIO_OVERVIEW: "portfolio-overview",
  ACCOUNT_PORTFOLIO_HISTORY: "account-portfolio-history",
  ACCOUNT_PORTFOLIO_OVERVIEW: "account-portfolio-overview",
  ACCOUNT_TRANSACTIONS: "account-transactions",
  USER_ASSETS: "user-assets",
  USER_ASSET_DETAIL: "user-asset-detail",
  USER_ASSET_PAIR: "user-asset-pair",
  USER_ASSET_PAIR_RATES: "user-asset-pair-rates",
  ASSET_TYPES: "asset-types",
  COMBINED_TRANSACTIONS: "combined-transactions",
};
