CREATE UNIQUE INDEX IF NOT EXISTS unique_asset_ticker ON assets(ticker);
CREATE UNIQUE INDEX IF NOT EXISTS unique_asset_pair ON asset_pairs(pair1, pair2);

ALTER TABLE assets ADD COLUMN IF NOT EXISTS isin TEXT NULL;
CREATE INDEX IF NOT EXISTS idx_assets_isin ON assets(isin) WHERE isin IS NOT NULL;

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS idx_assets_name_trgm ON assets USING gin (asset_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_assets_ticker_trgm ON assets USING gin (ticker gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_assets_ticker_lower ON assets (LOWER(ticker));

INSERT INTO asset_types (id, asset_type_name)
VALUES (1, 'Currencies'),
    (2, 'Stocks'),
    (3, 'Bonds'),
    (4, 'Mutual Funds'),
    (5, 'ETFs'),
    (6, 'ETCs'),
    (7, 'Cryptocurrencies'),
    (8, 'Real Estate')
ON CONFLICT (id) DO NOTHING;

INSERT INTO account_types (id, account_type_name)
VALUES (1, 'Current'),
    (2, 'Savings'),
    (3, 'Investment'),
    (4, 'Credit'),
    (5, 'Personal Pension'),
    (6, 'Workplace Pension'),
    (7, 'Mortgage'),
    (8, 'Loan'),
    (9, 'Real Estate'),
    (10, 'Crypto Wallet'),
    (11, 'Cash')
ON CONFLICT (id) DO NOTHING;

INSERT INTO account_liquidity_types (id, liquidity_type_name)
VALUES (1, 'Liquid')
ON CONFLICT (id) DO NOTHING;

INSERT INTO assets (asset_type, asset_name, ticker)
VALUES
    (1, 'UAE Dirham', 'AED'),
    (1, 'Afghani', 'AFN'),
    (1, 'Lek', 'ALL'),
    (1, 'Armenian Dram', 'AMD'),
    (1, 'Kwanza', 'AOA'),
    (1, 'Argentine Peso', 'ARS'),
    (1, 'Australian Dollar', 'AUD'),
    (1, 'Aruban Florin', 'AWG'),
    (1, 'Azerbaijan Manat', 'AZN'),
    (1, 'Convertible Mark', 'BAM'),
    (1, 'Barbados Dollar', 'BBD'),
    (1, 'Taka', 'BDT'),
    (1, 'Bulgarian Lev', 'BGN'),
    (1, 'Bahraini Dinar', 'BHD'),
    (1, 'Burundi Franc', 'BIF'),
    (1, 'Bermudian Dollar', 'BMD'),
    (1, 'Brunei Dollar', 'BND'),
    (1, 'Boliviano', 'BOB'),
    (1, 'Brazilian Real', 'BRL'),
    (1, 'Bahamian Dollar', 'BSD'),
    (1, 'Pula', 'BWP'),
    (1, 'Belarusian Ruble', 'BYN'),
    (1, 'Belize Dollar', 'BZD'),
    (1, 'Canadian Dollar', 'CAD'),
    (1, 'Congolese Franc', 'CDF'),
    (1, 'Swiss Franc', 'CHF'),
    (1, 'Chilean Unit of Account (CLF)', 'CLF'),
    (1, 'Chilean Peso', 'CLP'),
    (1, 'Chinese Yuan (Offshore)', 'CNH'),
    (1, 'Yuan Renminbi', 'CNY'),
    (1, 'Colombian Peso', 'COP'),
    (1, 'Costa Rican Colon', 'CRC'),
    (1, 'Cuban Peso', 'CUP'),
    (1, 'Cabo Verde Escudo', 'CVE'),
    (1, 'Czech Koruna', 'CZK'),
    (1, 'Djibouti Franc', 'DJF'),
    (1, 'Danish Krone', 'DKK'),
    (1, 'Dominican Peso', 'DOP'),
    (1, 'Algerian Dinar', 'DZD'),
    (1, 'Egyptian Pound', 'EGP'),
    (1, 'Ethiopian Birr', 'ETB'),
    (1, 'Euro', 'EUR'),
    (1, 'Fiji Dollar', 'FJD'),
    (1, 'Falkland Islands Pound', 'FKP'),
    (1, 'Pound Sterling', 'GBP'),
    (1, 'Lari', 'GEL'),
    (1, 'Ghanaian Cedi', 'GHS'),
    (1, 'Gibraltar Pound', 'GIP'),
    (1, 'Dalasi', 'GMD'),
    (1, 'Guinean Franc', 'GNF'),
    (1, 'Quetzal', 'GTQ'),
    (1, 'Guyana Dollar', 'GYD'),
    (1, 'Hong Kong Dollar', 'HKD'),
    (1, 'Lempira', 'HNL'),
    (1, 'Gourde', 'HTG'),
    (1, 'Forint', 'HUF'),
    (1, 'Rupiah', 'IDR'),
    (1, 'New Israeli Sheqel', 'ILS'),
    (1, 'Indian Rupee', 'INR'),
    (1, 'Iraqi Dinar', 'IQD'),
    (1, 'Iranian Rial', 'IRR'),
    (1, 'Iceland Krona', 'ISK'),
    (1, 'Jamaican Dollar', 'JMD'),
    (1, 'Jordanian Dinar', 'JOD'),
    (1, 'Yen', 'JPY'),
    (1, 'Kenyan Shilling', 'KES'),
    (1, 'Som', 'KGS'),
    (1, 'Riel', 'KHR'),
    (1, 'Comorian Franc', 'KMF'),
    (1, 'Won', 'KRW'),
    (1, 'Kuwaiti Dinar', 'KWD'),
    (1, 'Cayman Islands Dollar', 'KYD'),
    (1, 'Tenge', 'KZT'),
    (1, 'Lao Kip', 'LAK'),
    (1, 'Lebanese Pound', 'LBP'),
    (1, 'Sri Lanka Rupee', 'LKR'),
    (1, 'Liberian Dollar', 'LRD'),
    (1, 'Libyan Dinar', 'LYD'),
    (1, 'Moroccan Dirham', 'MAD'),
    (1, 'Moldovan Leu', 'MDL'),
    (1, 'Malagasy Ariary', 'MGA'),
    (1, 'Denar', 'MKD'),
    (1, 'Kyat', 'MMK'),
    (1, 'Pataca', 'MOP'),
    (1, 'Mauritanian Ouguiya', 'MRU'),
    (1, 'Mauritius Rupee', 'MUR'),
    (1, 'Rufiyaa', 'MVR'),
    (1, 'Malawi Kwacha', 'MWK'),
    (1, 'Mexican Peso', 'MXN'),
    (1, 'Malaysian Ringgit', 'MYR'),
    (1, 'Mozambique Metical', 'MZN'),
    (1, 'Namibia Dollar', 'NAD'),
    (1, 'Naira', 'NGN'),
    (1, 'Cordoba Oro', 'NIO'),
    (1, 'Norwegian Krone', 'NOK'),
    (1, 'Nepalese Rupee', 'NPR'),
    (1, 'New Zealand Dollar', 'NZD'),
    (1, 'Rial Omani', 'OMR'),
    (1, 'Balboa', 'PAB'),
    (1, 'Sol', 'PEN'),
    (1, 'Kina', 'PGK'),
    (1, 'Philippine Peso', 'PHP'),
    (1, 'Pakistan Rupee', 'PKR'),
    (1, 'Zloty', 'PLN'),
    (1, 'Guarani', 'PYG'),
    (1, 'Qatari Rial', 'QAR'),
    (1, 'Romanian Leu', 'RON'),
    (1, 'Serbian Dinar', 'RSD'),
    (1, 'Russian Ruble', 'RUB'),
    (1, 'Rwanda Franc', 'RWF'),
    (1, 'Saudi Riyal', 'SAR'),
    (1, 'Solomon Islands Dollar', 'SBD'),
    (1, 'Seychelles Rupee', 'SCR'),
    (1, 'Sudanese Pound', 'SDG'),
    (1, 'Swedish Krona', 'SEK'),
    (1, 'Singapore Dollar', 'SGD'),
    (1, 'Saint Helena Pound', 'SHP'),
    (1, 'Leone', 'SLL'),
    (1, 'Somali Shilling', 'SOS'),
    (1, 'El Salvador Colon', 'SVC'),
    (1, 'Lilangeni', 'SZL'),
    (1, 'Baht', 'THB'),
    (1, 'Turkmenistan New Manat', 'TMT'),
    (1, 'Tunisian Dinar', 'TND'),
    (1, 'Paanga', 'TOP'),
    (1, 'Turkish Lira', 'TRY'),
    (1, 'Trinidad and Tobago Dollar', 'TTD'),
    (1, 'New Taiwan Dollar', 'TWD'),
    (1, 'Tanzanian Shilling', 'TZS'),
    (1, 'Hryvnia', 'UAH'),
    (1, 'Uganda Shilling', 'UGX'),
    (1, 'US Dollar', 'USD'),
    (1, 'Peso Uruguayo', 'UYU'),
    (1, 'Uzbekistan Sum', 'UZS'),
    (1, 'Venezuelan Bolivar', 'VES'),
    (1, 'Dong', 'VND'),
    (1, 'CFA Franc BEAC', 'XAF'),
    (1, 'East Caribbean Dollar', 'XCD'),
    (1, 'CFA Franc BCEAO', 'XOF'),
    (1, 'CFP Franc', 'XPF'),
    (1, 'Yemeni Rial', 'YER'),
    (1, 'Rand', 'ZAR'),
    (1, 'Zambian Kwacha', 'ZMW'),
    (1, 'Zimbabwean Dollar', 'ZWL')
ON CONFLICT (ticker) DO NOTHING;

INSERT INTO asset_pairs (pair1, pair2)
VALUES
    ((SELECT id FROM assets WHERE ticker = 'AED'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'AED'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'AED'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'AED'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'AED'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'AED'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'AED'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'AED'), (SELECT id FROM assets WHERE ticker = 'NOK')),
    ((SELECT id FROM assets WHERE ticker = 'AED'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'AED'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'AED'), (SELECT id FROM assets WHERE ticker = 'SAR')),
    ((SELECT id FROM assets WHERE ticker = 'AED'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'AED'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'AED'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'ARS'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'ARS'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'ARS'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'ARS'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'ARS'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'AED')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'ARS')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'CNH')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'CZK')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'FJD')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'HUF')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'ILS')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'MXN')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'NOK')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'PHP')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'TRY')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'AUD'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'BDT'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'BDT'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'BDT'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'BHD'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'BHD'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'ARS')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'MXN')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'RUB')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'BRL'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'BWP'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'BWP'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'BWP'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'BYN'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'AED')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'ARS')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'CNH')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'CZK')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'ILS')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'ISK')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'KWD')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'MXN')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'NOK')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'RUB')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'TRY')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'CAD'), (SELECT id FROM assets WHERE ticker = 'ZMW')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'AED')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'ARS')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'BWP')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'CNH')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'CZK')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'HUF')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'ILS')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'ISK')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'MXN')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'NOK')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'RON')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'RUB')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'SZL')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'TRY')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'UZS')),
    ((SELECT id FROM assets WHERE ticker = 'CHF'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'CLF'), (SELECT id FROM assets WHERE ticker = 'CLP')),
    ((SELECT id FROM assets WHERE ticker = 'CLF'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'CLF'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'CLP'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'CLP'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'CNH'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'CNH'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'CNH'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'CNH'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'CNH'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'CNH'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'CNH'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'CNH'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'CNH'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'CNH'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'CZK')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'ILS')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'RUB')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'CNY'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'COP'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'CRC'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'CZK'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'CZK'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'CZK'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'CZK'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'CZK'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'CZK'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'CZK'), (SELECT id FROM assets WHERE ticker = 'NOK')),
    ((SELECT id FROM assets WHERE ticker = 'CZK'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'CZK'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'CZK'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'CZK')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'HUF')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'ISK')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'NOK')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'DKK'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'EGP'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'EGP'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'EGP'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'EGP'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'EGP'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'ETB'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'AED')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'AMD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'ARS')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'BGN')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'BHD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'CLP')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'CNH')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'COP')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'CRC')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'CZK')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'DZD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'EGP')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'FJD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'GEL')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'GHS')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'HUF')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'ILS')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'ISK')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'JOD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'KES')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'KWD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'KZT')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'LBP')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'LKR')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'MAD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'MKD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'MOP')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'MUR')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'MVR')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'MXN')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'NGN')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'NOK')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'OMR')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'PEN')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'PHP')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'QAR')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'RON')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'RSD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'RUB')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'SAR')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'SCR')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'TRY')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'TZS')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'UAH')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'VND')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'XOF')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'YER')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'EUR'), (SELECT id FROM assets WHERE ticker = 'ZMW')),
    ((SELECT id FROM assets WHERE ticker = 'FJD'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'AED')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'AFN')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'ALL')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'ARS')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'BDT')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'BHD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'BIF')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'BMD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'BND')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'BOB')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'BSD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'BWP')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'CLP')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'CNH')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'COP')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'CRC')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'CZK')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'DJF')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'DOP')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'DZD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'EGP')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'ETB')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'FJD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'GHS')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'GTQ')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'HNL')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'HTG')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'HUF')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'ILS')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'IQD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'ISK')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'JMD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'JOD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'KES')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'KWD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'LBP')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'LKR')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'MAD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'MUR')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'MVR')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'MWK')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'MXN')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'NGN')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'NIO')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'NOK')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'OMR')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'PEN')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'PGK')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'PHP')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'QAR')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'RON')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'RUB')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'SAR')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'SCR')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'SZL')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'TND')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'TRY')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'TTD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'TZS')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'UAH')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'UGX')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'VND')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'XAF')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'XCD')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'XPF')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'GBP'), (SELECT id FROM assets WHERE ticker = 'ZMW')),
    ((SELECT id FROM assets WHERE ticker = 'GHS'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'GHS'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'CNH')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'CZK')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'MXN')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'RUB')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'HKD'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'HUF'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'HUF'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'HUF'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'HUF'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'HUF'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'IDR'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'IDR'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'IDR'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'IDR'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'IDR'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'IDR'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'IDR'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'IDR'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'IDR'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'IDR'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'IDR'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'IDR'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'IDR'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'IDR'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'ILS'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'ILS'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'ILS'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'ILS'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'ILS'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'ILS'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'ILS'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'INR'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'ISK'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'ISK'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'ISK'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'JOD'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'ARS')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'CLP')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'CNH')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'CZK')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'ISK')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'MXN')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'NOK')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'RUB')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'JPY'), (SELECT id FROM assets WHERE ticker = 'ZMW')),
    ((SELECT id FROM assets WHERE ticker = 'KES'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'KES'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'KGS'), (SELECT id FROM assets WHERE ticker = 'RUB')),
    ((SELECT id FROM assets WHERE ticker = 'KRW'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'KRW'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'KRW'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'KRW'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'KRW'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'KRW'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'KRW'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'KRW'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'KRW'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'KRW'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'KRW'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'KRW'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'KRW'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'KWD'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'KWD'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'KWD'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'KWD'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'KYD'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'KZT'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'KZT'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'LKR'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'MAD'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'MAD'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'MDL'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'MKD'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'MUR'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'MUR'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'MXN'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'MXN'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'MXN'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'MXN'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'MXN'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'MXN'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'MXN'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'MXN'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'MXN'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'MXN'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'MXN'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'MXN'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'MXN'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'CNH')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'MYR'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'NAD'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'NGN'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'NGN'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'NGN'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'NOK'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'NOK'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'NOK'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'NOK'), (SELECT id FROM assets WHERE ticker = 'CNH')),
    ((SELECT id FROM assets WHERE ticker = 'NOK'), (SELECT id FROM assets WHERE ticker = 'CZK')),
    ((SELECT id FROM assets WHERE ticker = 'NOK'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'NOK'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'NOK'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'NOK'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'NOK'), (SELECT id FROM assets WHERE ticker = 'ISK')),
    ((SELECT id FROM assets WHERE ticker = 'NOK'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'NOK'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'NOK'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'NOK'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'NOK'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'AED')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'CNH')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'CZK')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'HUF')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'MXN')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'NOK')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'PHP')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'NZD'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'OMR'), (SELECT id FROM assets WHERE ticker = 'AED')),
    ((SELECT id FROM assets WHERE ticker = 'OMR'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'OMR'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'OMR'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'OMR'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'PAB'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'PEN'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'PEN'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'PGK'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'PHP'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'PHP'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'PHP'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'PHP'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'PHP'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'PKR'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'PKR'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'PKR'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'PKR'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'PKR'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'PLN'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'PLN'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'PLN'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'PLN'), (SELECT id FROM assets WHERE ticker = 'CZK')),
    ((SELECT id FROM assets WHERE ticker = 'PLN'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'PLN'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'PLN'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'PLN'), (SELECT id FROM assets WHERE ticker = 'HUF')),
    ((SELECT id FROM assets WHERE ticker = 'PLN'), (SELECT id FROM assets WHERE ticker = 'ILS')),
    ((SELECT id FROM assets WHERE ticker = 'PLN'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'PLN'), (SELECT id FROM assets WHERE ticker = 'RON')),
    ((SELECT id FROM assets WHERE ticker = 'PLN'), (SELECT id FROM assets WHERE ticker = 'RUB')),
    ((SELECT id FROM assets WHERE ticker = 'PLN'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'PLN'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'QAR'), (SELECT id FROM assets WHERE ticker = 'AED')),
    ((SELECT id FROM assets WHERE ticker = 'QAR'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'QAR'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'QAR'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'QAR'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'RON'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'RON'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'RON'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'RUB'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'RUB'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'RUB'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'RUB'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'RUB'), (SELECT id FROM assets WHERE ticker = 'ILS')),
    ((SELECT id FROM assets WHERE ticker = 'RUB'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'RUB'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'RUB'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'RUB'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'SAR'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'SAR'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'SAR'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'SAR'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'CNH')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'CZK')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'ILS')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'ISK')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'NOK')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'SEK'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'ARS')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'CNH')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'MXN')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'NOK')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'VND')),
    ((SELECT id FROM assets WHERE ticker = 'SGD'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'SZL'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'SZL'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'VND')),
    ((SELECT id FROM assets WHERE ticker = 'THB'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'TND'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'TRY'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'TRY'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'TRY'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'TRY'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'TRY'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'TRY'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'TRY'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'TRY'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'TRY'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'TTD'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'TTD'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'TWD'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'TZS'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'UAH'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'UGX'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'UGX'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'AED')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'AFN')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'ALL')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'AMD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'AOA')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'ARS')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'AWG')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'AZN')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'BAM')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'BBD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'BDT')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'BHD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'BIF')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'BMD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'BND')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'BOB')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'BSD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'BWP')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'BYN')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'BZD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'CDF')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'CLP')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'CNH')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'COP')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'CRC')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'CUP')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'CVE')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'CZK')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'DJF')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'DOP')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'DZD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'EGP')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'ETB')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'FJD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'FKP')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'GEL')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'GHS')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'GIP')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'GMD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'GNF')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'GTQ')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'GYD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'HNL')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'HTG')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'HUF')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'ILS')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'IQD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'IRR')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'ISK')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'JMD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'JOD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'KES')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'KHR')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'KMF')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'KWD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'KYD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'KZT')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'LAK')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'LBP')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'LKR')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'LRD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'LYD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'MAD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'MDL')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'MGA')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'MKD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'MMK')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'MOP')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'MRU')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'MVR')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'MWK')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'MXN')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'MZN')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'NAD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'NGN')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'NIO')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'NOK')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'NPR')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'OMR')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'PAB')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'PEN')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'PGK')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'PHP')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'PYG')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'QAR')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'RON')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'RSD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'RUB')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'RWF')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'SAR')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'SBD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'SCR')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'SDG')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'SHP')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'SLL')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'SOS')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'SVC')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'SZL')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'TMT')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'TND')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'TOP')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'TRY')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'TTD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'TZS')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'UAH')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'UGX')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'UYU')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'UZS')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'VES')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'VND')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'XAF')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'XOF')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'XPF')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'YER')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'ZAR')),
    ((SELECT id FROM assets WHERE ticker = 'USD'), (SELECT id FROM assets WHERE ticker = 'ZMW')),
    ((SELECT id FROM assets WHERE ticker = 'UYU'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'VND'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'VND'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'XAF'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'XCD'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'XOF'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'XOF'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'XOF'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'AED')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'AUD')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'BRL')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'BWP')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'CHF')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'CNY')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'DKK')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'EUR')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'HKD')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'IDR')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'INR')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'KES')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'KRW')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'MXN')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'MYR')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'NOK')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'NZD')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'PHP')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'PKR')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'PLN')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'RUB')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'SEK')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'SGD')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'THB')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'TWD')),
    ((SELECT id FROM assets WHERE ticker = 'ZAR'), (SELECT id FROM assets WHERE ticker = 'USD')),
    ((SELECT id FROM assets WHERE ticker = 'ZMW'), (SELECT id FROM assets WHERE ticker = 'CAD')),
    ((SELECT id FROM assets WHERE ticker = 'ZMW'), (SELECT id FROM assets WHERE ticker = 'GBP')),
    ((SELECT id FROM assets WHERE ticker = 'ZMW'), (SELECT id FROM assets WHERE ticker = 'JPY')),
    ((SELECT id FROM assets WHERE ticker = 'ZWL'), (SELECT id FROM assets WHERE ticker = 'ZAR'))
ON CONFLICT (pair1, pair2) DO NOTHING;

-- Reset sequences after explicit ID inserts
SELECT setval('asset_types_id_seq', (SELECT MAX(id) FROM asset_types));
SELECT setval('account_types_id_seq', (SELECT MAX(id) FROM account_types));
SELECT setval('account_liquidity_types_id_seq', (SELECT MAX(id) FROM account_liquidity_types));
