/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthShellRouteImport } from './routes/_auth/_shell'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthShellIndexRouteImport } from './routes/_auth/_shell/index'
import { Route as AuthShellAiChatRouteImport } from './routes/_auth/_shell/ai-chat'
import { Route as AuthShellSettingsRouteImport } from './routes/_auth/_shell/settings'
import { Route as AuthShellTransactionsRouteImport } from './routes/_auth/_shell/transactions'
import { Route as AuthShellAccountsIndexRouteImport } from './routes/_auth/_shell/accounts.index'
import { Route as AuthShellAccountsAccountIdRouteImport } from './routes/_auth/_shell/accounts.$accountId'
import { Route as AuthShellPortfolioIndexRouteImport } from './routes/_auth/_shell/portfolio.index'
import { Route as AuthShellPortfolioAssetIdRouteImport } from './routes/_auth/_shell/portfolio.$assetId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthShellRoute = AuthShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthShellIndexRoute = AuthShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthShellRoute,
} as any)
const AuthShellAiChatRoute = AuthShellAiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => AuthShellRoute,
} as any)
const AuthShellSettingsRoute = AuthShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthShellRoute,
} as any)
const AuthShellTransactionsRoute = AuthShellTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthShellRoute,
} as any)
const AuthShellAccountsIndexRoute = AuthShellAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AuthShellRoute,
} as any)
const AuthShellAccountsAccountIdRoute =
  AuthShellAccountsAccountIdRouteImport.update({
    id: '/accounts/$accountId',
    path: '/accounts/$accountId',
    getParentRoute: () => AuthShellRoute,
  } as any)
const AuthShellPortfolioIndexRoute = AuthShellPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => AuthShellRoute,
} as any)
const AuthShellPortfolioAssetIdRoute =
  AuthShellPortfolioAssetIdRouteImport.update({
    id: '/portfolio/$assetId',
    path: '/portfolio/$assetId',
    getParentRoute: () => AuthShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthShellIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/ai-chat': typeof AuthShellAiChatRoute
  '/settings': typeof AuthShellSettingsRoute
  '/transactions': typeof AuthShellTransactionsRoute
  '/accounts/$accountId': typeof AuthShellAccountsAccountIdRoute
  '/portfolio/$assetId': typeof AuthShellPortfolioAssetIdRoute
  '/accounts/': typeof AuthShellAccountsIndexRoute
  '/portfolio/': typeof AuthShellPortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthShellIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/ai-chat': typeof AuthShellAiChatRoute
  '/settings': typeof AuthShellSettingsRoute
  '/transactions': typeof AuthShellTransactionsRoute
  '/accounts/$accountId': typeof AuthShellAccountsAccountIdRoute
  '/portfolio/$assetId': typeof AuthShellPortfolioAssetIdRoute
  '/accounts': typeof AuthShellAccountsIndexRoute
  '/portfolio': typeof AuthShellPortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_auth/_shell': typeof AuthShellRouteWithChildren
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/_shell/ai-chat': typeof AuthShellAiChatRoute
  '/_auth/_shell/settings': typeof AuthShellSettingsRoute
  '/_auth/_shell/transactions': typeof AuthShellTransactionsRoute
  '/_auth/_shell/': typeof AuthShellIndexRoute
  '/_auth/_shell/accounts/$accountId': typeof AuthShellAccountsAccountIdRoute
  '/_auth/_shell/portfolio/$assetId': typeof AuthShellPortfolioAssetIdRoute
  '/_auth/_shell/accounts/': typeof AuthShellAccountsIndexRoute
  '/_auth/_shell/portfolio/': typeof AuthShellPortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/onboarding'
    | '/ai-chat'
    | '/settings'
    | '/transactions'
    | '/accounts/$accountId'
    | '/portfolio/$assetId'
    | '/accounts/'
    | '/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/onboarding'
    | '/ai-chat'
    | '/settings'
    | '/transactions'
    | '/accounts/$accountId'
    | '/portfolio/$assetId'
    | '/accounts'
    | '/portfolio'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/_auth/_shell'
    | '/_auth/onboarding'
    | '/_auth/_shell/ai-chat'
    | '/_auth/_shell/settings'
    | '/_auth/_shell/transactions'
    | '/_auth/_shell/'
    | '/_auth/_shell/accounts/$accountId'
    | '/_auth/_shell/portfolio/$assetId'
    | '/_auth/_shell/accounts/'
    | '/_auth/_shell/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_shell': {
      id: '/_auth/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthShellRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_shell/': {
      id: '/_auth/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthShellIndexRouteImport
      parentRoute: typeof AuthShellRoute
    }
    '/_auth/_shell/ai-chat': {
      id: '/_auth/_shell/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AuthShellAiChatRouteImport
      parentRoute: typeof AuthShellRoute
    }
    '/_auth/_shell/settings': {
      id: '/_auth/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthShellSettingsRouteImport
      parentRoute: typeof AuthShellRoute
    }
    '/_auth/_shell/transactions': {
      id: '/_auth/_shell/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthShellTransactionsRouteImport
      parentRoute: typeof AuthShellRoute
    }
    '/_auth/_shell/accounts/': {
      id: '/_auth/_shell/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthShellAccountsIndexRouteImport
      parentRoute: typeof AuthShellRoute
    }
    '/_auth/_shell/accounts/$accountId': {
      id: '/_auth/_shell/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AuthShellAccountsAccountIdRouteImport
      parentRoute: typeof AuthShellRoute
    }
    '/_auth/_shell/portfolio/': {
      id: '/_auth/_shell/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof AuthShellPortfolioIndexRouteImport
      parentRoute: typeof AuthShellRoute
    }
    '/_auth/_shell/portfolio/$assetId': {
      id: '/_auth/_shell/portfolio/$assetId'
      path: '/portfolio/$assetId'
      fullPath: '/portfolio/$assetId'
      preLoaderRoute: typeof AuthShellPortfolioAssetIdRouteImport
      parentRoute: typeof AuthShellRoute
    }
  }
}

interface AuthShellRouteChildren {
  AuthShellAiChatRoute: typeof AuthShellAiChatRoute
  AuthShellSettingsRoute: typeof AuthShellSettingsRoute
  AuthShellTransactionsRoute: typeof AuthShellTransactionsRoute
  AuthShellIndexRoute: typeof AuthShellIndexRoute
  AuthShellAccountsAccountIdRoute: typeof AuthShellAccountsAccountIdRoute
  AuthShellPortfolioAssetIdRoute: typeof AuthShellPortfolioAssetIdRoute
  AuthShellAccountsIndexRoute: typeof AuthShellAccountsIndexRoute
  AuthShellPortfolioIndexRoute: typeof AuthShellPortfolioIndexRoute
}

const AuthShellRouteChildren: AuthShellRouteChildren = {
  AuthShellAiChatRoute: AuthShellAiChatRoute,
  AuthShellSettingsRoute: AuthShellSettingsRoute,
  AuthShellTransactionsRoute: AuthShellTransactionsRoute,
  AuthShellIndexRoute: AuthShellIndexRoute,
  AuthShellAccountsAccountIdRoute: AuthShellAccountsAccountIdRoute,
  AuthShellPortfolioAssetIdRoute: AuthShellPortfolioAssetIdRoute,
  AuthShellAccountsIndexRoute: AuthShellAccountsIndexRoute,
  AuthShellPortfolioIndexRoute: AuthShellPortfolioIndexRoute,
}

const AuthShellRouteWithChildren = AuthShellRoute._addFileChildren(
  AuthShellRouteChildren,
)

interface AuthRouteChildren {
  AuthShellRoute: typeof AuthShellRouteWithChildren
  AuthOnboardingRoute: typeof AuthOnboardingRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthShellRoute: AuthShellRouteWithChildren,
  AuthOnboardingRoute: AuthOnboardingRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
