import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.ktlint)
    alias(libs.plugins.detekt)
}

// ── Rust core build integration ─────────────────────────────────────────────
// Automatically cross-compiles the Rust core and generates UniFFI bindings
// before Kotlin compilation. Debug builds target only arm64 for speed;
// release builds target all ABIs.

val coreDir = rootProject.file("../server/app-core")
val workspaceTargetDir = rootProject.file("../server/target")
val jniLibsDir = file("src/main/jniLibs")
val bindingsDir = file("src/main/java")

val abiToTarget =
    mapOf(
        "arm64-v8a" to "aarch64-linux-android",
        "armeabi-v7a" to "armv7-linux-androideabi",
        "x86_64" to "x86_64-linux-android",
        "x86" to "i686-linux-android",
    )

val isReleaseBuild =
    gradle.startParameter.taskNames.any {
        it.contains("Release", ignoreCase = true)
    }
val targetAbis = if (isReleaseBuild) abiToTarget.keys.toList() else listOf("arm64-v8a")

// Resolve cargo binary — Android Studio doesn't inherit shell PATH
val cargoHome = System.getenv("CARGO_HOME") ?: "${System.getProperty("user.home")}/.cargo"
val cargo = "$cargoHome/bin/cargo"

tasks.register("buildRustCore") {
    description = "Cross-compile Rust core for Android and generate UniFFI bindings"
    inputs.dir(coreDir.resolve("src"))
    inputs.file(coreDir.resolve("Cargo.toml"))
    outputs.dir(jniLibsDir)

    doLast {
        for (abi in targetAbis) {
            val target = abiToTarget[abi]!!
            providers
                .exec {
                    workingDir = coreDir
                    commandLine(cargo, "ndk", "--target", target, "--platform", "24", "--", "build", "--release")
                }.result
                .get()
            val dest = jniLibsDir.resolve(abi)
            dest.mkdirs()
            workspaceTargetDir.resolve("$target/release/libsverto_core.so").copyTo(dest.resolve("libsverto_core.so"), overwrite = true)
        }

        // Generate Kotlin bindings from the first built .so
        val firstTarget = abiToTarget[targetAbis.first()]!!
        val soPath = workspaceTargetDir.resolve("$firstTarget/release/libsverto_core.so")
        providers
            .exec {
                workingDir = coreDir
                commandLine(
                    cargo,
                    "run",
                    "--release",
                    "--bin",
                    "uniffi-bindgen",
                    "--",
                    "generate",
                    "--library",
                    soPath.absolutePath,
                    "--language",
                    "kotlin",
                    "--out-dir",
                    bindingsDir.absolutePath,
                )
            }.result
            .get()
    }
}

tasks
    .matching {
        (it.name.startsWith("compile") && it.name.contains("Kotlin")) ||
            it.name.startsWith("merge") &&
            it.name.contains("JniLibFolders")
    }.configureEach {
        dependsOn("buildRustCore")
    }

// Read config from the project root .env file (generated by `make setup-env`)
val envFile =
    rootProject.file("../.env").let { f ->
        mutableMapOf<String, String>().also { map ->
            if (f.exists()) {
                f.readLines().forEach { line ->
                    val trimmed = line.trim()
                    if (trimmed.isNotEmpty() && !trimmed.startsWith("#") && '=' in trimmed) {
                        val (k, v) = trimmed.split("=", limit = 2)
                        map[k.trim()] = v.trim()
                    }
                }
            }
        }
    }

val appEnv = project.findProperty("APP_ENV") as String? ?: envFile["APP_ENV"] ?: "dev"
val isProd = appEnv == "prod"

android {
    namespace = "com.sverto.app"
    compileSdk = 36

    defaultConfig {
        minSdk = 24
        targetSdk = 36
        versionCode = 1
        versionName = "0.1.0"

        ndk {
            abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86_64", "x86")
        }

        // Gradle properties (-P) override .env values
        val clerkKey =
            project.findProperty("CLERK_PUBLISHABLE_KEY") as String?
                ?: envFile["CLERK_PUBLISHABLE_KEY"] ?: ""
        buildConfigField("String", "CLERK_PUBLISHABLE_KEY", "\"$clerkKey\"")

        val serverPort = envFile["SERVER_PORT"] ?: "7002"
        val apiBaseUrl =
            project.findProperty("APP_API_BASE_URL") as String?
                ?: envFile["APP_API_BASE_URL"]
                ?: "http://localhost:$serverPort"
        buildConfigField("String", "API_BASE_URL", "\"$apiBaseUrl\"")
    }

    signingConfigs {
        create("app") {
            // Resolves absolute paths as-is, relative paths from project root
            val storePath =
                project.findProperty("SVERTO_STORE_FILE") as String?
                    ?: envFile["SVERTO_STORE_FILE"]
            storeFile =
                storePath?.let { path ->
                    val f = file(path)
                    if (f.exists()) f else rootProject.file("../$path")
                }
            storePassword = project.findProperty("SVERTO_STORE_PASSWORD") as String?
                ?: envFile["SVERTO_STORE_PASSWORD"] ?: ""
            keyAlias = project.findProperty("SVERTO_KEY_ALIAS") as String?
                ?: envFile["SVERTO_KEY_ALIAS"] ?: ""
            keyPassword = project.findProperty("SVERTO_KEY_PASSWORD") as String?
                ?: envFile["SVERTO_KEY_PASSWORD"] ?: ""
        }
    }

    flavorDimensions += "environment"
    productFlavors {
        create("dev") {
            dimension = "environment"
            applicationId = "com.sverto.app.dev"
        }
        create("prod") {
            dimension = "environment"
            applicationId = "com.sverto.app"
        }
    }

    buildTypes {
        debug {
            signingConfig = signingConfigs.getByName("app")
            // Prod flavor uses release keystore even for debug builds
        }
        release {
            signingConfig = signingConfigs.getByName("app")
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }

    // Auto-select flavor based on APP_ENV in .env
    androidComponents {
        beforeVariants { variant ->
            val flavorName = variant.productFlavors.find { it.first == "environment" }?.second
            // Disable variants that don't match the current env
            if (flavorName != null && flavorName != appEnv) {
                variant.enable = false
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
    }
}

// ── Linting & formatting ────────────────────────────────────────────────────
ktlint {
    android = true
    filter {
        exclude("**/uniffi/**")
    }
}

detekt {
    config.setFrom(rootProject.file("detekt.yml"))
    buildUponDefaultConfig = true
    source.setFrom("src/main/java/com/sverto")
}

tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach {
    jvmTarget = "17"
}
tasks.withType<io.gitlab.arturbosch.detekt.DetektCreateBaselineTask>().configureEach {
    jvmTarget = "17"
}

dependencies {
    detektPlugins("io.nlopez.compose.rules:detekt:0.4.22")
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation("androidx.compose.material:material-icons-core")
    implementation("androidx.compose.material:material-icons-extended")
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.viewmodel.compose)
    implementation(libs.lifecycle.runtime.compose)
    implementation(libs.core.ktx)

    // Pin material3 to alpha for M3 Expressive (MaterialExpressiveTheme, MotionScheme, new shapes)
    implementation("androidx.compose.material3:material3:1.5.0-alpha16")

    // Clerk authentication
    implementation(libs.clerk.api)
    implementation(libs.clerk.ui)

    // Navigation
    implementation(libs.navigation.compose)


    // JNA is required by UniFFI-generated Kotlin code to call into native libraries
    implementation(libs.jna) { artifact { type = "aar" } }

    debugImplementation(libs.compose.ui.tooling)
}
