INSERT INTO asset_types (name)
VALUES ('Currencies'),
    ('Stocks'),
    ('Bonds'),
    ('Mutual Funds'),
    ('ETFs'),
    ('Commodities'),
    ('Real Estate'),
    ('Cryptocurrencies'),
    ('Options'),
    ('Futures'),
    ('Derivatives'),
    ('Art'),
    ('Collectibles'),
    ('Precious Metals');
INSERT INTO assets (asset_type, name, ticker)
VALUES (1, 'US Dollar', 'USD'),
    (1, 'Euro', 'EUR'),
    (1, 'Japanese Yen', 'JPY'),
    (1, 'British Pound', 'GBP'),
    (1, 'Swiss Franc', 'CHF'),
    (1, 'Canadian Dollar', 'CAD'),
    (1, 'Australian Dollar', 'AUD'),
    (1, 'New Zealand Dollar', 'NZD'),
    (1, 'Chinese Yuan', 'CNY'),
    (1, 'Hong Kong Dollar', 'HKD'),
    (2, 'Apple Inc.', 'AAPL'),
    (2, 'Microsoft Corporation', 'MSFT'),
    (2, 'Amazon.com, Inc.', 'AMZN'),
    (2, 'Alphabet Inc. Class A', 'GOOGL'),
    (2, 'Facebook, Inc. Class A', 'FB'),
    (2, 'Tesla, Inc.', 'TSLA'),
    (2, 'Berkshire Hathaway Inc. Class B', 'BRK.B'),
    (2, 'JPMorgan Chase & Co.', 'JPM'),
    (2, 'Johnson & Johnson', 'JNJ'),
    (2, 'Procter & Gamble Company', 'PG'),
    (2, 'Visa Inc. Class A', 'V'),
    (2, 'NVIDIA Corporation', 'NVDA'),
    (2, 'Walmart Inc.', 'WMT'),
    (2, 'Mastercard Incorporated Class A', 'MA'),
    (2, 'UnitedHealth Group Incorporated', 'UNH'),
    (2, 'The Home Depot, Inc.', 'HD'),
    (2, 'PayPal Holdings, Inc.', 'PYPL'),
    (2, 'Walt Disney Company', 'DIS'),
    (2, 'Verizon Communications Inc.', 'VZ'),
    (2, 'Intel Corporation', 'INTC'),
    (2, 'Salesforce.com Inc.', 'CRM'),
    (2, 'Bank of America Corporation', 'BAC'),
    (2, 'Coca-Cola Company', 'KO'),
    (2, 'Pfizer Inc.', 'PFE'),
    (2, 'Netflix, Inc.', 'NFLX'),
    (2, 'Cisco Systems, Inc.', 'CSCO'),
    (2, 'Chevron Corporation', 'CVX'),
    (2, 'AT&T Inc.', 'T'),
    (2, 'Abbott Laboratories', 'ABT'),
    (2, 'Merck & Co., Inc.', 'MRK'),
    (2, 'Exxon Mobil Corporation', 'XOM'),
    (2, 'The Goldman Sachs Group, Inc.', 'GS'),
    (2, 'General Electric Company', 'GE'),
    (2, 'Accenture plc Class A', 'ACN'),
    (2, 'Honeywell International Inc.', 'HON'),
    (2, '3M Company', 'MMM'),
    (2, 'American Express Company', 'AXP'),
    (2, 'The Boeing Company', 'BA'),
    (2, 'Morgan Stanley', 'MS'),
    (2, 'Medtronic plc', 'MDT'),
    (2, 'The Coca-Cola Company', 'KO'),
    (2, 'McDonalds Corporation', 'MCD'),
    (2, 'The Charles Schwab Corporation', 'SCHW'),
    (2, 'Raytheon Technologies Corporation', 'RTX'),
    (2, 'CVS Health Corporation', 'CVS'),
    (2, 'Bristol-Myers Squibb Company', 'BMY'),
    (2, 'Caterpillar Inc.', 'CAT'),
    (2, 'NextEra Energy, Inc.', 'NEE'),
    (8, 'Bitcoin', 'BTC'),
    (8, 'Ethereum', 'ETH'),
    (8, 'Binance Coin', 'BNB'),
    (8, 'Cardano', 'ADA'),
    (8, 'Dogecoin', 'DOGE'),
    (8, 'XRP', 'XRP'),
    (8, 'Solana', 'SOL'),
    (8, 'Polkadot', 'DOT'),
    (8, 'Chainlink', 'LINK'),
    (8, 'Litecoin', 'LTC'),
    (5, 'SPDR S&P 500 ETF', 'SPY'),
    (5, 'Invesco QQQ ETF', 'QQQ'),
    (5, 'Vanguard Total Stock Market ETF', 'VTI'),
    (5, 'SPDR Gold Shares ETF', 'GLD'),
    (5, 'iShares MSCI EAFE ETF', 'EFA'),
    (5, 'iShares Russell 2000 ETF', 'IWM'),
    (5, 'Vanguard Total Bond Market ETF', 'BND'),
    (5, 'iShares Core S&P Mid-Cap ETF', 'IJH'),
    (5, 'Invesco S&P 500 Equal Weight ETF', 'RSP');
INSERT INTO user_roles (name)
VALUES ('User'),
    ('Admin');
INSERT INTO transaction_categories (category)
VALUES ('Income'),
    ('Groceries'),
    ('Fuel'),
    ('Home improvement'),
    ('Entertainment'),
    ('Dining'),
    ('Shopping'),
    ('Travel'),
    ('Insurance'),
    ('Investment'),
    ('Utilities'),
    ('Rent'),
    ('Mortgage'),
    ('Healthcare'),
    ('Childcare'),
    ('Education'),
    ('Charity'),
    ('Taxes'),
    ('Pets'),
    ('Gifts'),
    ('Savings'),
    ('Miscellaneous'),
    ('Clothing'),
    ('Electronics'),
    ('Hobbies'),
    ('Sports'),
    ('Books'),
    ('Movies'),
    ('Music'),
    ('Vacation'),
    ('Gardening'),
    ('Toys'),
    ('Office supplies'),
    ('Beauty'),
    ('Alcohol'),
    ('Coffee'),
    ('Internet'),
    ('Phone'),
    ('Car payments'),
    ('Car insurance'),
    ('Public transportation'),
    ('Car repairs'),
    ('Home decor'),
    ('Pet food'),
    ('Fast food'),
    ('Snacks'),
    ('Alumni donations'),
    ('Credit card fees'),
    ('Postage'),
    ('Parking'),
    ('Home security');
INSERT INTO users (id, username, password, default_asset, role)
VALUES (
        '2396480f-0052-4cf0-81dc-8cedbde5ce13',
        'einaras',
        '$argon2id$v=19$m=19456,t=2,p=1$cA/2g90uUzqvdHXniTwyBA$WIbpl9GH5JD93dpkDT8gHkMQOMeeNZkqhI5OKUS8/uc',
        1,
        2
    );