INSERT INTO asset_types (name)
VALUES ('Currencies'),
    ('Stocks'),
    ('Bonds'),
    ('Mutual Funds'),
    ('ETFs'),
    ('Commodities'),
    ('Real Estate'),
    ('Cryptocurrencies'),
    ('Options'),
    ('Futures'),
    ('Derivatives'),
    ('Art'),
    ('Collectibles'),
    ('Precious Metals');
INSERT INTO assets (asset_type, name, ticker)
VALUES (1, 'US Dollar', 'USD'),
    (1, 'Euro', 'EUR'),
    (1, 'British Pound', 'GBP');
INSERT INTO user_roles (name)
VALUES ('User'),
    ('Admin');
INSERT INTO transaction_categories (category, icon)
VALUES ('Income', 'attach_money'),
    ('Groceries', 'local_grocery_store'),
    ('Fuel', 'local_gas_station'),
    ('Home improvement', 'home'),
    ('Entertainment', 'movie'),
    ('Dining', 'restaurant'),
    ('Shopping', 'shopping_basket'),
    ('Travel', 'flight'),
    ('Insurance', 'insurance'),
    ('Investment', 'trending_up'),
    ('Utilities', 'settings'),
    ('Rent', 'house'),
    ('Mortgage', 'home_work'),
    ('Healthcare', 'local_hospital'),
    ('Childcare', 'child_friendly'),
    ('Education', 'school'),
    ('Charity', 'favorite'),
    ('Taxes', 'money_off'),
    ('Pets', 'pets'),
    ('Gifts', 'card_giftcard'),
    ('Savings', 'account_balance'),
    ('Miscellaneous', 'layers'),
    ('Clothing', 'clothes'),
    ('Electronics', 'devices'),
    ('Hobbies', 'sports_esports'),
    ('Sports', 'sports'),
    ('Books', 'menu_book'),
    ('Movies', 'theaters'),
    ('Music', 'music_note'),
    ('Vacation', 'beach_access'),
    ('Gardening', 'eco'),
    ('Toys', 'toys'),
    ('Office supplies', 'work'),
    ('Beauty', 'face'),
    ('Alcohol', 'local_bar'),
    ('Coffee', 'local_cafe'),
    ('Internet', 'wifi'),
    ('Phone', 'phone'),
    ('Car payments', 'directions_car'),
    ('Car insurance', 'safety_divider'),
    ('Public transportation', 'directions_transit'),
    ('Car repairs', 'build'),
    ('Home decor', 'home'),
    ('Pet food', 'pets'),
    ('Fast food', 'fastfood'),
    ('Snacks', 'free_breakfast'),
    ('Alumni donations', 'favorite'),
    ('Credit card fees', 'credit_card'),
    ('Postage', 'mail'),
    ('Parking', 'local_parking'),
    ('Home security', 'security');
INSERT INTO users (id, username, password, default_asset, role)
VALUES (
        '2396480f-0052-4cf0-81dc-8cedbde5ce13',
        'einaras',
        '$argon2id$v=19$m=19456,t=2,p=1$cA/2g90uUzqvdHXniTwyBA$WIbpl9GH5JD93dpkDT8gHkMQOMeeNZkqhI5OKUS8/uc',
        1,
        2
    );
INSERT INTO portfolio_account (id, user_id, name)
VALUES (
        '2396480f-0052-4cf0-81dc-8cedbde5ce13',
        '2396480f-0052-4cf0-81dc-8cedbde5ce13',
        'Default'
    );