name: Rust CI

on:
  push:
    branches: [ workflows ]
  pull_request:
    branches: [ workflows ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Check
      run: cargo check
      working-directory: ./server

    - name: Clippy
      run: cargo clippy -- -D warnings
      working-directory: ./server

    - name: Format Check
      run: cargo fmt -- --check
      working-directory: ./server
